const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={risk:48,rain:85,moisture:62,alerts:[{id:'ALT-1042',level:'critical',title:'Critical landslide warning',place:'East Sikkim',score:91,status:'ACTIVE',time:'12 min ago'},{id:'ALT-1039',level:'high',title:'Slope instability watch',place:'Tawang, Arunachal Pradesh',score:74,status:'ACKNOWLEDGED',time:'38 min ago'},{id:'ALT-1037',level:'moderate',title:'Rainfall threshold crossed',place:'Ri Bhoi, Meghalaya',score:48,status:'ACTIVE',time:'1 hr ago'}]};
const metrics=[['Total monitored zones','1,250+','↑ 4 this week'],['High-risk zones','48','↑ 6 since 06:00'],['Critical zones','12','↑ 2 active'],['Active sensors','327','96% connected'],['Reports today','26','↑ 18%'],['People potentially at risk','18,420','Across 31 locations']];
$('#metrics').innerHTML=metrics.map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
const sensorData=[['RG-102','Rain Gauge','East Sikkim','18.4 mm/h','NORMAL','93%'],['SM-204','Soil Moisture','Sikkim Zone 4','82%','WARNING','91%'],['GM-018','Ground Movement','Tawang Ridge','2.1 mm','NORMAL','88%'],['WS-077','Weather Station','Ri Bhoi','24.6°C','NORMAL','96%'],['SM-137','Soil Moisture','Mizoram Corridor','76%','WARNING','89%'],['RG-302','Rain Gauge','Shillong','11.2 mm/h','NORMAL','94%']];
$('#sensorGrid').innerHTML=sensorData.map(s=>`<article class="sensor-card"><div class="sensor-top"><span>${s[0]}</span><span style="color:${s[4]==='WARNING'?'var(--yellow)':'var(--aqua)'}">● ${s[4]}</span></div><h3>${s[1]}</h3><span>${s[2]}</span><strong>${s[3]}</strong><footer><span>Updated 12 sec ago</span><span>Battery ${s[5]}</span></footer></article>`).join('');
const incidents=[['INC-2026-028','East Sikkim','Slope Movement','Critical','Citizen report','RESPONDING','N. Tamang'],['INC-2026-027','Tawang','Road Blockage','High','Sensor network','VERIFIED','P. Deka'],['INC-2026-026','Ri Bhoi','Ground Crack','Moderate','Field officer','SUBMITTED','Unassigned'],['INC-2026-025','Champhai','Rockfall','High','Citizen report','RESPONDING','L. Zama']];
$('#incidentRows').innerHTML=incidents.map(i=>`<tr>${i.map((v,n)=>`<td>${n===3?`<span class="tag ${v.toLowerCase()}">${v}</span>`:n===5?`<span class="tag ${v==='RESPONDING'?'high':'resolved'}">${v}</span>`:v}</td>`).join('')}</tr>`).join('');
function renderAlerts(){const markup=state.alerts.map(a=>`<div class="alert-card"><div class="severity ${a.level}"></div><div><span class="eyebrow">${a.id} · ${a.status} · ${a.score}%</span><h3>${a.title} — ${a.place}</h3><p>Heavy rainfall and elevated soil moisture require field coordination.</p></div><div class="alert-actions"><button onclick="updateAlert('${a.id}','ACKNOWLEDGED')">Acknowledge</button><button onclick="updateAlert('${a.id}','RESOLVED')">Resolve</button></div></div>`).join('');$('#alertList').innerHTML=markup;$('#dashboardAlerts').innerHTML=state.alerts.slice(0,3).map(a=>`<div class="alert-row"><span class="severity ${a.level}"></span><div><strong>${a.title}</strong><small>${a.place} · ${a.score}% risk</small></div><em>${a.time}</em></div>`).join('');$('#alertBadge').textContent=state.alerts.filter(a=>a.status==='ACTIVE').length}
window.updateAlert=(id,status)=>{let a=state.alerts.find(a=>a.id===id);a.status=status;renderAlerts();toast(`${id} marked ${status.toLowerCase()}.`)};renderAlerts();
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#pageTitle').textContent={dashboard:'Command Center',map:'Live GIS Risk Map',prediction:'AI Prediction Center',alerts:'Early Warning & Alert Center',sensors:'Sensor & Environmental Monitoring',incidents:'Incident Management',report:'Citizen Reporting',analytics:'Historical Analytics',admin:'Admin Dashboard'}[id];window.scrollTo(0,0)}
$$('#nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));
function level(score){return score>=76?'CRITICAL':score>=51?'HIGH':score>=26?'MODERATE':'LOW'}function tone(l){return l==='CRITICAL'?'var(--red)':l==='HIGH'?'var(--orange)':l==='MODERATE'?'var(--yellow)':'var(--lime)'}
function calculate(fd){const rain=Math.min(+fd.get('rainfall')/180,1)*25,moist=Math.min(+fd.get('moisture')/100,1)*20,slope=Math.min(+fd.get('slope')/55,1)*20,hist=Math.min(+fd.get('history')/10,1)*15,forecast=Math.min(+fd.get('forecast')/180,1)*10,stability=(1-(+fd.get('stability')/100))*10;return Math.round(rain+moist+slope+hist+forecast+stability)}
$('#predictionForm').onsubmit=e=>{e.preventDefault();const score=calculate(new FormData(e.target));setRisk(score);toast(`Risk analysis complete: ${score}% ${level(score)}.`)};
function setRisk(score){state.risk=score;let l=level(score),color=tone(l);$('#predictionScore').textContent=score+'%';$('#predictionLevel').textContent=l+' RISK';$('.gauge').style.background=`conic-gradient(${color} 0 ${score}%,#254249 ${score}% 100%)`;$('#predictionScore').style.color=color;$('#predictionLevel').style.color=color;$('#heroRisk').textContent=score+'%';$('#heroRisk').style.color=color;$('#heroLevel').textContent=l;$('#heroLevel').style.color=color;$('#aiExplanation').textContent=l==='CRITICAL'?'Extreme rainfall, saturated soil and steep terrain indicate urgent slope instability. Initiate evacuation readiness and inspect roads.':l==='HIGH'?'Conditions are escalating. Deploy field inspection teams and increase sensor polling.':'Current conditions require monitoring. Review rainfall updates every 30 minutes.'}
$('#simulate').onclick=()=>{toast('Live simulation started: extreme rainfall front approaching East Sikkim.');let steps=[[68,130,74],[89,165,84]],n=0;let timer=setInterval(()=>{let [risk,rain,moist]=steps[n++];state.rain=rain;state.moisture=moist;$('#rainfall').textContent=rain+' mm';$('#moisture').textContent=moist+'%';$('#sensorRain').textContent=(rain/7).toFixed(1)+' mm/h';$('#sensorSoil').textContent=moist+'%';setRisk(risk);if(risk>=76&&!state.alerts.some(a=>a.id==='ALT-1048')){state.alerts.unshift({id:'ALT-1048',level:'critical',title:'Critical landslide warning',place:'East Sikkim',score:risk,status:'ACTIVE',time:'now'});renderAlerts();toast('CRITICAL WARNING generated — East Sikkim. Authorities notified.')}if(n===2)clearInterval(timer)},2200)};
$$('.pin').forEach(p=>p.onclick=()=>{let loc=p.dataset.location;$('#locationPanel h2').textContent=loc;$('#mapRisk').textContent=loc==='East Sikkim'?state.risk+'%':'74%';toast(`${loc} risk profile loaded.`)});
$('#reportForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Report submitted successfully — REP-2281. Status: SUBMITTED.');showPage('incidents')};$('#locationBtn').onclick=()=>{toast('Demo location set to: Gangtok, Sikkim.');};$('#newAlert').onclick=()=>toast('New-alert composer would open here in production.');
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>el.classList.remove('show'),4500)}setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})},1000);setRisk(48);
